apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: webapp-service-account
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - secretRef:
            name: {{ .Values.container.secretName }}
        env:
        - name: MONGO_DB_URL
          value: mongodb.mongodb.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.container.port }}