---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webservice-role
rules:
  - apiGroups: [""]
    resources: ["secret"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webapp-role-binding
subjects:
  - kind: ServiceAccount
    name: webapp-service-account
    namespace: webapp-namespace
roleRef:
  kind: Role
  name: webapp-role
  apiGroup: rbac.authorization.k8s.io  