apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.secretName }}
type: Opaque
data:
  MONGO_DB_USERNMAE: {{ .Values.db_connection.MONGO_DB_USERNMAE}}
  MONGO_DB_PASSWORD: {{ .Values.db_connection.MONGO_DB_PASSWORD}}
